version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scrpits/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scrpts/start_container.sh
      timeout: 300
      runas: root
